[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
wasmtime.workspace = true
tokio.workspace = true
thiserror.workspace = true
clap.workspace = true

sdk.workspace = true
